// Generated by wxt
export {}
declare global {
  const A2aAgentManager: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/components/A2aAgentManager').A2aAgentManager
  const ChatInput: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/components/ChatInput').ChatInput
  const ChatInterface: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/components/ChatInterface').ChatInterface
  const CodeBlock: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/components/CodeBlock').CodeBlock
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const McpServerManager: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/components/McpServerManager').McpServerManager
  const MessageBubble: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/components/MessageBubble').MessageBubble
  const ServerStatus: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/components/ServerStatus').ServerStatus
  const ToolCallIndicator: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/components/ToolCallIndicator').ToolCallIndicator
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const storage: typeof import('wxt/utils/storage').storage
  const useA2aAgents: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/hooks/useA2aAgents').useA2aAgents
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useChat: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/hooks/useChat').useChat
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMcpServers: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/hooks/useMcpServers').useMcpServers
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useServerHealth: typeof import('C:/Users/sungb/Documents/GitHub/AgentHub/extension/hooks/useServerHealth').useServerHealth
  const useState: typeof import('react').useState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
